### ISSUE TITLE
Split username, device into two fields on UI

### ISSUE THREAD

**Issue by jpmens** [owntracks/traction#5]
Ben says: 
> is it worth separating out the login field into two lines, one for `User ID` and `Device ID` so it marries up exactly with what needs to be entered into the apps?

Maybe useful. OTOH, confusing to `mosquitto_sub` users

**Comment by sumnerboy12** [comment]
Who are we targeting with `traction` tho? Owntracks app users or `mosquitto_sub` users?

**Comment by jpmens** [comment]
App users.

**Comment by sumnerboy12** [comment]
Then I would argue we should separate the field - make it as easy for users to config their Owntracks app as possible. With perhaps a note indicating the mosquitto login in subscript?

**Comment by jpmens** [comment]
Not the note please; I don't want it there. It will be in _booklet_ and I think that's enough.

As to the fields: let's postpone this until we've settled on UI labels in the apps. I think the labeling of the Web UI will then seem trivial.  :-)

**Comment by sumnerboy12** [comment]
I was just trying to appease your 'OTOH' comment ;).

**Comment by sumnerboy12** [comment]
Looks like traction has been updated to show `User ID`, `Password`, and `Device ID`, and the iOS app is now showing `User`, `Device` and `Token`. I think these need to be identical to ensure minimal user confusion. I think `Token` is a better name, since the user already has a _password_ for logging into traction.

**Comment by jpmens** [comment]
I've changed to `User`, `Device` and `Token` for the time being.
